Update from integration template

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -16,22 +16,44 @@ jobs:
     name: "Hassfest Validation"
     runs-on: "ubuntu-latest"
     steps:
-        - name: "Checkout the repository"
-          uses: "actions/checkout@v4.0.0"
+      - name: "Checkout the repository"
+        uses: "actions/checkout@v4"
 
-        - name: "Run hassfest validation"
-          uses: "home-assistant/actions/hassfest@master"
+      - name: "Run hassfest validation"
+        uses: "home-assistant/actions/hassfest@master"
 
   hacs: # https://github.com/hacs/action
     name: "HACS Validation"
     runs-on: "ubuntu-latest"
     steps:
-        - name: "Checkout the repository"
-          uses: "actions/checkout@v4.0.0"
+      - name: "Checkout the repository"
+        uses: "actions/checkout@v4"
 
-        - name: "Run HACS validation"
-          uses: "hacs/action@main"
-          with:
-            category: "integration"
-            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
-            ignore: "brands"
+      - name: "Run HACS validation"
+        uses: "hacs/action@main"
+        with:
+          category: "integration"
+          # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
+          ignore: "brands"
+
+  misc:
+    name: Misc Validation
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Check Home Assistant version consistency
+        shell: bash
+        run: |
+          hacs_req=$(yq -r -oj .homeassistant hacs.json) || exit
+          project_req=$(
+            content=$(<pyproject.toml) || exit
+            if [[ "$content" =~ homeassistant==([0-9.]+) ]]; then
+              echo "${BASH_REMATCH[1]}"
+            fi
+          )
+
+          if [ "$hacs_req" != "$project_req" ]; then
+            echo "::error file=hacs.json::HACS version requirement for HA doesn't match requirement from pyproject.toml"
+            exit 1
+          fi
